#!/usr/bin/env bash
##
## EPITECH PROJECT, 2020
## Functionnals test
## File description:
## Test on execution 
##

## OBJECTIF : Nous faire segfault (tester juste si la return value de -sh est égale à 0)